
// Declare the foreign function from parser.c (generated by tree-sitter)
//vba-parser/src/lib.rs
unsafe extern "C" {
    fn tree_sitter_vba() -> tree_sitter::Language;
}

pub fn language() -> tree_sitter::Language {
    unsafe { tree_sitter_vba() }
}
